// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnLHdQQPoMJj-N9F6uWtsO6qCnrooPO8',
    appId: '1:1025336674419:web:3b7231557ca71a58574206',
    messagingSenderId: '1025336674419',
    projectId: 'cookhub-3ba90',
    authDomain: 'cookhub-3ba90.firebaseapp.com',
    storageBucket: 'cookhub-3ba90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3dm5IwvyGoKqjUd5aYhky9t_LVPIA9o',
    appId: '1:1025336674419:android:32b7687b6a78e05c574206',
    messagingSenderId: '1025336674419',
    projectId: 'cookhub-3ba90',
    storageBucket: 'cookhub-3ba90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMwUnRJhHMYDjn63eRNRSYARSIVVLXBJE',
    appId: '1:1025336674419:ios:1b694f2e3514c08b574206',
    messagingSenderId: '1025336674419',
    projectId: 'cookhub-3ba90',
    storageBucket: 'cookhub-3ba90.appspot.com',
    iosBundleId: 'com.example.cookhubFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMwUnRJhHMYDjn63eRNRSYARSIVVLXBJE',
    appId: '1:1025336674419:ios:1b694f2e3514c08b574206',
    messagingSenderId: '1025336674419',
    projectId: 'cookhub-3ba90',
    storageBucket: 'cookhub-3ba90.appspot.com',
    iosBundleId: 'com.example.cookhubFrontend',
  );
}
